# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/Basys-3-Master.xdc

# Block Designs: bd/OLED2/OLED2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2 || ORIG_REF_NAME==OLED2} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_microblaze_0_0/OLED2_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_microblaze_0_0 || ORIG_REF_NAME==OLED2_microblaze_0_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_mdm_1_0/OLED2_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_mdm_1_0 || ORIG_REF_NAME==OLED2_mdm_1_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_clk_wiz_1_0/OLED2_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_clk_wiz_1_0 || ORIG_REF_NAME==OLED2_clk_wiz_1_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_rst_clk_wiz_1_100M_0/OLED2_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==OLED2_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_axi_uartlite_0_0/OLED2_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_axi_uartlite_0_0 || ORIG_REF_NAME==OLED2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_axi_gpio_0_0/OLED2_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_axi_gpio_0_0 || ORIG_REF_NAME==OLED2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_PmodGPIO_0_0/OLED2_PmodGPIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_PmodGPIO_0_0 || ORIG_REF_NAME==OLED2_PmodGPIO_0_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_PmodGPIO_1_0/OLED2_PmodGPIO_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_PmodGPIO_1_0 || ORIG_REF_NAME==OLED2_PmodGPIO_1_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_microblaze_0_axi_periph_0/OLED2_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==OLED2_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_xbar_0/OLED2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_xbar_0 || ORIG_REF_NAME==OLED2_xbar_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_dlmb_v10_0/OLED2_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_dlmb_v10_0 || ORIG_REF_NAME==OLED2_dlmb_v10_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_ilmb_v10_0/OLED2_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_ilmb_v10_0 || ORIG_REF_NAME==OLED2_ilmb_v10_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_dlmb_bram_if_cntlr_0/OLED2_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==OLED2_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_ilmb_bram_if_cntlr_0/OLED2_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==OLED2_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/OLED2/ip/OLED2_lmb_bram_0/OLED2_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED2_lmb_bram_0 || ORIG_REF_NAME==OLED2_lmb_bram_0} -quiet] -quiet

# XDC: bd/OLED2/OLED2_ooc.xdc
