# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Student/Desktop/152B_Labs_Turner_Liu/capstone/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_clk_wiz_1_0/OLEDrgb_clk_wiz_1_0.xci
# IP: The module: 'OLEDrgb_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Student/Desktop/152B_Labs_Turner_Liu/capstone/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_clk_wiz_1_0/OLEDrgb_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLEDrgb_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Student/Desktop/152B_Labs_Turner_Liu/capstone/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_clk_wiz_1_0/OLEDrgb_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLEDrgb_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Student/Desktop/152B_Labs_Turner_Liu/capstone/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_clk_wiz_1_0/OLEDrgb_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLEDrgb_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Student/Desktop/152B_Labs_Turner_Liu/capstone/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_clk_wiz_1_0/OLEDrgb_clk_wiz_1_0.xci
# IP: The module: 'OLEDrgb_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Student/Desktop/152B_Labs_Turner_Liu/capstone/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_clk_wiz_1_0/OLEDrgb_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLEDrgb_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Student/Desktop/152B_Labs_Turner_Liu/capstone/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_clk_wiz_1_0/OLEDrgb_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLEDrgb_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Student/Desktop/152B_Labs_Turner_Liu/capstone/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_clk_wiz_1_0/OLEDrgb_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLEDrgb_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
