webtalk_init -webtalk_dir C:\\Users\\Leo\\Desktop\\Engineering\\capstone\\capstone-master\\capstone-master\\capstone\\OLED_RGB\\capstone.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-06-06 19:59:52" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212588100_0_0_777" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "gd8qo9pe0j5juurh6f4nimuh0j" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 7900X 12-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4700 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.508 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1717729139682" -context "sdk\\\\hardware/1717729139682"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1717729139682"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1717729139682"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1717729139682"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1717729139682"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1717729139682"
webtalk_add_data -client sdk -key Device -value "7a35t" -context "sdk\\\\hardware/1717729139682"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1717729139682"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1717729139682"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1717729139682"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1717729139682"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1717729192742"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1717729192742"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1717729192742"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1717729192742"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1717729192742"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1717729192742"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1717729192742"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1717729192742"
webtalk_transmit -clientid 3793022253 -regid "212588100_0_0_777" -xml C:\\Users\\Leo\\Desktop\\Engineering\\capstone\\capstone-master\\capstone-master\\capstone\\OLED_RGB\\capstone.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Leo\\Desktop\\Engineering\\capstone\\capstone-master\\capstone-master\\capstone\\OLED_RGB\\capstone.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Leo\\Desktop\\Engineering\\capstone\\capstone-master\\capstone-master\\capstone\\OLED_RGB\\capstone.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
