# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/OLEDrgb/OLEDrgb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb || ORIG_REF_NAME==OLEDrgb} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_microblaze_0_0/OLEDrgb_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_microblaze_0_0 || ORIG_REF_NAME==OLEDrgb_microblaze_0_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_mdm_1_0/OLEDrgb_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_mdm_1_0 || ORIG_REF_NAME==OLEDrgb_mdm_1_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_clk_wiz_1_0/OLEDrgb_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_clk_wiz_1_0 || ORIG_REF_NAME==OLEDrgb_clk_wiz_1_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_rst_clk_wiz_1_100M_0/OLEDrgb_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==OLEDrgb_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_axi_uartlite_0_0/OLEDrgb_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_axi_uartlite_0_0 || ORIG_REF_NAME==OLEDrgb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_microblaze_0_axi_periph_0/OLEDrgb_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==OLEDrgb_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_PmodOLEDrgb_0_1/OLEDrgb_PmodOLEDrgb_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_PmodOLEDrgb_0_1 || ORIG_REF_NAME==OLEDrgb_PmodOLEDrgb_0_1} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_axi_gpio_0_0/OLEDrgb_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_axi_gpio_0_0 || ORIG_REF_NAME==OLEDrgb_axi_gpio_0_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_xbar_0/OLEDrgb_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_xbar_0 || ORIG_REF_NAME==OLEDrgb_xbar_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_dlmb_v10_0/OLEDrgb_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_dlmb_v10_0 || ORIG_REF_NAME==OLEDrgb_dlmb_v10_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_ilmb_v10_0/OLEDrgb_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_ilmb_v10_0 || ORIG_REF_NAME==OLEDrgb_ilmb_v10_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_dlmb_bram_if_cntlr_0/OLEDrgb_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==OLEDrgb_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_ilmb_bram_if_cntlr_0/OLEDrgb_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==OLEDrgb_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/OLEDrgb/ip/OLEDrgb_lmb_bram_0/OLEDrgb_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLEDrgb_lmb_bram_0 || ORIG_REF_NAME==OLEDrgb_lmb_bram_0} -quiet] -quiet

# XDC: bd/OLEDrgb/OLEDrgb_ooc.xdc
