webtalk_init -webtalk_dir C:\\Users\\Student\\Desktop\\152B_Labs_Turner_Liu\\capstone\\capstone.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-06-03 14:50:47" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211888400_0_0_236" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9egk3le3ed1q506g5mr68c0d0r" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_65" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "65" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.411 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1717451339267" -context "sdk\\\\bsp/1717451339267"
webtalk_add_data -client sdk -key hwid -value "1717448506573" -context "sdk\\\\bsp/1717451339267"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1717451339267"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1717451339267"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1717451339267"
webtalk_add_data -client sdk -key uid -value "1717451342469" -context "sdk\\\\application/1717451342469"
webtalk_add_data -client sdk -key hwid -value "1717448506573" -context "sdk\\\\application/1717451342469"
webtalk_add_data -client sdk -key bspid -value "1717451339267" -context "sdk\\\\application/1717451342469"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1717451342469"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1717451342469"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1717451342469"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1717451342469"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1717451342469"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1717451342469"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1717451447045"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1717451447045"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1717451447045"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1717451447045"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1717451447045"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1717451447045"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1717451447045"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1717451447045"
webtalk_transmit -clientid 201399540 -regid "211888400_0_0_236" -xml C:\\Users\\Student\\Desktop\\152B_Labs_Turner_Liu\\capstone\\capstone.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Student\\Desktop\\152B_Labs_Turner_Liu\\capstone\\capstone.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Student\\Desktop\\152B_Labs_Turner_Liu\\capstone\\capstone.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
