# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Student/Downloads/capstone-master/capstone-master/capstone/OLED_RGB/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_xbar_0/OLEDrgb_xbar_0.xci
# IP: The module: 'OLEDrgb_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Student/Downloads/capstone-master/capstone-master/capstone/OLED_RGB/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_xbar_0/OLEDrgb_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLEDrgb_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Student/Downloads/capstone-master/capstone-master/capstone/OLED_RGB/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_xbar_0/OLEDrgb_xbar_0.xci
# IP: The module: 'OLEDrgb_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Student/Downloads/capstone-master/capstone-master/capstone/OLED_RGB/capstone.srcs/sources_1/bd/OLEDrgb/ip/OLEDrgb_xbar_0/OLEDrgb_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLEDrgb_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
