# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Student/Downloads/OLED2/OLED2.srcs/sources_1/bd/OLED2/ip/OLED2_mdm_1_0/OLED2_mdm_1_0.xci
# IP: The module: 'OLED2_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Student/Downloads/OLED2/OLED2.srcs/sources_1/bd/OLED2/ip/OLED2_mdm_1_0/OLED2_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLED2_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Student/Downloads/OLED2/OLED2.srcs/sources_1/bd/OLED2/ip/OLED2_mdm_1_0/OLED2_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLED2_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Student/Downloads/OLED2/OLED2.srcs/sources_1/bd/OLED2/ip/OLED2_mdm_1_0/OLED2_mdm_1_0.xci
# IP: The module: 'OLED2_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Student/Downloads/OLED2/OLED2.srcs/sources_1/bd/OLED2/ip/OLED2_mdm_1_0/OLED2_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLED2_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Student/Downloads/OLED2/OLED2.srcs/sources_1/bd/OLED2/ip/OLED2_mdm_1_0/OLED2_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLED2_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
